spring:
  application:
    name: cinema_crud
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/your_database_name?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: mysql/?????
    password: mysql/?????
  mustache:
    suffix: .html
    servlet:
      cache: false

server:
  port: 8880
