spring:
  application:
    name: swimpool_app
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/swimmingpool_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: swimmer
    password: 1q2w3e4r!
  mustache:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    charset: UTF-8
    servlet:
      cache: false

server:
  port: 8082
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true